[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1

[Metadata]
Name=FunPay Price
Author=ProUser
Version=1.0

[Variables]
fontName=Trebuchet MS
textSize=10
colorText=255,255,255,205
colorAccent=235,170,0,255

; ----------------------------------
; MEASURES
; ----------------------------------

[measurePrice]
Measure=Plugin
Plugin=WebParser
URL=file://D:\Funpay\price.txt
RegExp=(.*)
StringIndex=1
UpdateRate=300
DefaultValue=Loading...

; ----------------------------------
; STYLES
; ----------------------------------

[styleTitle]
StringAlign=Left
StringCase=Upper
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorAccent#
FontFace=#fontName#
FontSize=12
AntiAlias=1

[styleText]
StringAlign=Right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1

[styleSeparator]
SolidColor=255,255,255,50

; ----------------------------------
; METERS
; ----------------------------------

[meterTitle]
Meter=String
MeterStyle=styleTitle
X=10
Y=12
Text=Цена дивана

[meterSeparator]
Meter=Image
MeterStyle=styleSeparator
X=10
Y=32
W=160
H=1

[meterPriceLabel]
Meter=String
MeterStyle=styleText
StringAlign=Left
X=10
Y=42
Text=Минималка сейчас:

[meterPriceValue]
Meter=String
MeterStyle=styleText
MeasureName=measurePrice
X=170
Y=0r
Text=%1 ₽